### ISSUE TITLE
Example showing how to use rules_js in multiproject monorepo

### ISSUE THREAD

**Issue by tannerwelsh** [aspect-build/bazel-examples#108]
Hey Aspect folks! Our team has been using some of the Bazel rules you've maintained in our projects (currently in the process of migrating to using `rules_js`), and we are super grateful for the work that you do.

One example that we'd like to see in this repo is for a **single workspace that supports multiple different Node.js packages** to demonstrate how one could use Bazel + `rules_js` to create a setup with:

- [x] Separate, isolated npm/pnpm dependencies between packages (i.e. no single shared `package.json` for the workspace). Could use https://pnpm.io/workspaces here.
- [x] Code sharing across packages (i.e. for a component library used by multiple web app packages).
- [x] Bazel targets for running the standard Next.js commands `dev`/`build`/`serve`/`lint`, with hot reload enabled for `dev` server. Follow up: Acknowledging that a `dev` and `lint` might be out of scope for this issue.
- [x] ~Examples of Jest tests in each package, including snapshot tests.~ Already captured in https://github.com/aspect-build/rules_jest/issues/17

Let's say there are two packages in this workspace:

- `ts-library` : a library exporting React components and TypeScript modules
- `next-app` : a generic Next.js app following the [next.js example](https://github.com/aspect-build/bazel-examples/tree/main/next.js), which makes use of components from `ts-library`

The example workspace structure could look like this:

```
README.md
WORKSPACE
packages/
  next-app/
    BUILD.bazel
    package.json
    ... other files for Next.js app
  ts-library/
    BUILD.bazel
    package.json
    ... other files for a TypeScript package
  ... any other packages that might be useful to show
```

**Comment by alexeagle** [comment]
This one is already being tracked:
- https://github.com/aspect-build/rules_jest/issues/17

Linting is busted right now because of the way eslint tries to extend from the next.js config. @gregmagolan will file an issue about that separately, it's probably a separate project.

The devserver in next.js currently restarts on each Bazel rebuild, it needs to be taught the `ibazel_notify_changes` protocol from https://github.com/bazelbuild/bazel-watcher#running-a-target. It looks to me like https://nextjs.org/docs/advanced-features/custom-server might give us the affordance to run their devserver but control when they refresh content from the disk. It will take a bit of experimentation to confirm.

**Comment by tannerwelsh** [comment]
> This one is already being tracked:
> 
> * [jest_test should also create a run target to update snapshots rules_jest#17](https://github.com/aspect-build/rules_jest/issues/17)

Thanks! Updated the description to strike that from the specs.

Re: linting and dev servers, thanks for the explanation re: why these would be more complicated. To start, these shouldn't be necessary for development so long as there's an option to run these commands outside of the Bazel context, i.e. with scripts in a `package.json` like:

```json
  "scripts": {
    "dev": "next dev",
    "build": "bazel build //:build",
    "start": "ibazel run //:start",
    "lint": "next lint"
  },
```

**Comment by tannerwelsh** [comment]
Just contributed funding for this issue on https://opencollective.com/aspect-build/projects/rules_js (payment from Twisp)

**Comment by gregmagolan** [comment]
@tannerwelsh I made some progress on this this week. It doesn't look feasible (at least not without big patches to Next.js and webpack) to adapt the next.js devserver to play nicely with how Bazel lays out the runfiles of a binary so I abandoned that approach and now have a general purpose devserver/watchmode rule going in rules_js that instead adapts Bazel to what the Next.js devserver expects to find on disk. https://github.com/aspect-build/rules_js/pull/540.

Should have something merged here sometime next week.

**Comment by gregmagolan** [comment]
Landed the change to generalize the next targets into a portable `next()` macro and add a working ibazel `next dev` devserver. https://github.com/aspect-build/bazel-examples/commit/772bf64da1d1a8a9e9e47239b586a7060fe8d09f

Will still add an example up code sharing here in the next day or two.

**Comment by tannerwelsh** [comment]
That's great, thanks @gregmagolan! Looking forward to seeing it in action

**Comment by gregmagolan** [comment]
@tannerwelsh This PR should address the remaining items in your list: https://github.com/aspect-build/bazel-examples/pull/128

LMK how it works out on your end and if you need anything else shown in here.

**Comment by gregmagolan** [comment]
PR landed

**Comment by tannerwelsh** [comment]
Dang this is looking great, thanks @gregmagolan ! I just did some preliminary poking around, and everything looks like it should translate nicely to our system. Once I get deeper into the weeds of translating this example into a real-world context, I'll follow up with any feedback/snags I bump into.

Thanks also to @alexeagle for coordinating! Really happy with the way this worked out.
