### ISSUE TITLE
[FR]: Example of Angular project with gRPC-web

### ISSUE THREAD

**Issue by gonzojive** [aspect-build/bazel-examples#141]
### What is the current behavior?

It's possible to write the app, but I'm not quite sure how.

### Describe the feature

An example of an Angular application that communicates with a backend using gRPC-web would be pretty helpful. A teammate of mine or I will probably get to this at some point, but I want to put out the desire for this in advance. Here is what I'm thinking:

- [ ] An extremely minimal angular application with a single web page
- [ ] An extremely minimal proto definition like https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/helloworld/helloworld.proto
- [ ] An extremely simple gRPC-web backend, probably in Go
- [ ] An extremely simple HTTP backend for serving static content, probably in Go

I built something like this with rules_nodejs, which I copied from the rules_nodejs examples. I consider the Angular app way more complicated than it needs to be. https://github.com/gonzojive/example-ts-go-grpc-bazel/tree/master/viz/src/app

---

We are currently using rules_nodejs for an Angular app with gRPC-web. It works but is brittle, and I often run into trouble getting protos to work properly. The tsconfig.json file contains a mess of `rootDirs` specifying `bazel-bin` dirs. When `tsc` fails to resolve an import dependency, its error message doesn't give debug info about what paths were searched to try to satisfy the import. I am hoping rules_js/rules_ts will be better.

I'll look into sponsoring a bounty when I have a chance.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by dprogm** [comment]
I am also going to use Bazel+Angular+gRPC, so maybe I can help out here. Generating Angular compatible typescript is already done here: https://github.com/dprogm/angular-grpc-example Next step is to put the generated code into a `ts_project` and provide a fully fledged client-server-app based on `angular-ngc`. This should be straightforward though. :sunglasses:

**Comment by dprogm** [comment]
Just want to share a rather complete example: https://github.com/dprogm/angular-grpc-example
Maybe it is helpful for someone facing the same problem. 😇

**Comment by alexeagle** [comment]
This is funded now, see https://opencollective.com/protobuf-and-grpc/contributions/684301
Thanks Finn!

Spec: Extend the https://github.com/aspect-build/bazel-examples/tree/main/angular-ngc example to show communication with a gRPC server backend. It should use the https://github.com/bufbuild/connect-es protocol buffer plugin for producing code, as the Google Protobuf team is moving to this as the "official" stubs for TypeScript. It will use the current bazelbuild/rules_proto Bazel ruleset as a base layer, but should take minimal additional dependencies.
