### ISSUE TITLE
Add sass example in next.js

### ISSUE THREAD

**Issue by paulfariello** [aspect-build/bazel-examples#163]
### What is the current behavior?

The next.js example project demonstrate how to setup a project with a lib and some typescript but styling is only done with css while next.js allows to work easily with Sass.

### Describe the feature

Add a `.scss` file in the styles directory and show how to build it. Would be nice to have support for sass dependencies.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by ztl8702** [comment]
It appears that https://github.com/bazelbuild/rules_sass/tree/main/sass is a very thin wrapper around npm package `sass`

so should be easy to re-implement. 

_(just thinking out loud. not claiming that I am going to it.)_

**Comment by alexeagle** [comment]
I agree with @ztl8702 that rules_sass doesn't give much useful behavior that you don't get by using the npm package directly, and adds complexity and maybe-Google-abandonware.

**Comment by paulfariello** [comment]
Bazel newbie here, I'm having some difficulties understanding how `js_binary` should be used to use the sass npm package directly to build sass.

Either using a simple macro:
```python
load("@npm//client/build-config:sass/package_json.bzl", sass_bin = "bin")

def sass(name, srcs, deps = []):
    sass_bin.sass(
        name = "_%s_sass" % name,
        srcs = srcs + deps,
        outs = [_sass_out(src) for src in srcs] + ["%s.map" % _sass_out(src) for src in srcs],
        args = [
            "--load-path=node_modules",
        ] + [
            "$(execpath {}):{}/{}".format(src, native.package_name(), _sass_out(src))
            for src in srcs
        ],
        visibility = ["//visibility:private"],
    )
```

but it end up missing transitive dependencies (since they are not linked in the `node_modules` inside the sandbox).

Or trying to define a rule using ctx.action.run with an executable set from a `js_binary` but there is quite a gap to understand how to copy all dependencies to the bin directory (iiuc https://github.com/aspect-build/rules_js/tree/main#running-nodejs-programs).
