### ISSUE TITLE
Question: How to add CSS from third party package?

### ISSUE THREAD

**Issue by dprogm** [aspect-build/bazel-examples#188]
I am currently working on integrating a large Angular project into a Bazel monorepo. The project uses [Clarity](https://clarity.design/documentation/get-started) as a UI framework but I guess my question also applies to other frameworks such as Material. Normally you add the CSS from package `@clr/ui` to the corresponding `angular.json` file. 

How is it possible to add a CSS file from a thiry party package?

I checked the example of [rules_nodejs](https://github.com/bazelbuild/rules_nodejs/blob/stable/examples/angular/src/BUILD.bazel) and they are adding the CSS file by referencing it directly. My current approach is adding the CSS in `defs.bzl:`
```
APPLICATION_HTML_ASSETS = ["styles.css", "favicon.ico", "//:node_modules/@clr/ui/clr-ui.min.css"]
```
But I get the following error:
```
no such target '//:node_modules/@clr/ui/clr-ui.min.css'
```
I checked the documentation but I cannot figure out what targets are defined for each dependency declared in `package.json`

I would be grateful for help and hope it is the right place for this kind of question.

**Comment by gregmagolan** [comment]
If you're just requiring the `@clr/ui` to be available for the build target or a binary/test target it is sufficient to add `//:node_modules/@clr/ui` to `deps` or `data` and then all of those files are available at runtime.

The reason `//:node_modules/@clr/ui` is opaque is that that particular target is just a symlink to the virtual store where the actual npm package is located. rules_js uses a [symlinked node_modules structure](https://pnpm.io/symlinked-node-modules-structure) under the hood. The actual virtual store target (which isn't typically referenced directory in user facing BUILD files) is a directory (tree) artifact so it is also opaque and you can't make labels to files within it. That target does have a convenient alias, however: `//:node_modules/@clr/ui/dir` that you can use in combination with a `directory_path` rule to reference the file within the npm package. From there, it can be used in downstream rules that are `directory_path` aware such as `copy_file`, `copy_to_directory`, `write_source_files` or `npm_package`.

For example,

```
directory_path(
   name = "clr_ui_min_css",
   directory = "//:node_modules/@clr/ui/dir",
   path = "clr-ui.min.css",
)
```

and then you can use that target in `copy_file` (which copies that file to the output tree):"

```
copy_file(
    name = "copy_clr_ui_min_css",
    src = ":clr_ui_min_css",
    out = "clr-ui.min.css",
)
``

or if you wanted it in checked-in in the source tree you could do the same with a `write_source_files` target which would copy it to the source tree and checks that it stays up to date with a `diff_test`

**Comment by gregmagolan** [comment]
Those rules are all found in our bazel-lib utility rule set: https://docs.aspect.build/rules/aspect_bazel_lib

**Comment by gregmagolan** [comment]
I'll leave this open and close it once we add some docs for how to do this and a working example in bazel-examples.

**Comment by dprogm** [comment]
Thank you. I just tried it out and added the target `copy_clr_ui_min_css` to `APPLICATION_HTML_ASSETS`. In the output tree I can see the CSS file correctly but when I look at the developer console I see something different. Obviously this is not the requested CSS. Did I miss something?

![clr_ui](https://user-images.githubusercontent.com/32619672/220570128-079b03b4-b7c9-4099-af88-d6982594e123.png)
