### ISSUE TITLE
[Bug]: react-cra example isn't building

### ISSUE THREAD

**Issue by kourtni** [aspect-build/bazel-examples#240]
### What happened?

When I try to build the `build` target in the [react-cra](https://github.com/aspect-build/bazel-examples/tree/main/react-cra) example project I get an error saying:
``` shell
ERROR: Skipping 'react-cra:build': error loading package 'react-cra': cannot load '@npm//:react-scripts/package_json.bzl': no such file
```

As a note, I've tried on both Bazel 6.2.1 and Bazel 6.1.2 (which is the version your repository is pinned to).

### Version

Development (host) and target OS/architectures: WSL/2

Output of `bazel --version`:
``` shell
Bazelisk version: development
Build label: 6.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 2 16:59:58 2023 (1685725198)
Build timestamp: 1685725198
Build timestamp as int: 1685725198
```

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
``` starlark
http_archive(
    name = "aspect_rules_js",
    sha256 = "e3e6c3d42491e2938f4239a3d04259a58adc83e21e352346ad4ef62f87e76125",
    strip_prefix = "rules_js-1.30.0",
    url = "https://github.com/aspect-build/rules_js/releases/download/v1.30.0/rules_js-v1.30.0.tar.gz",
)
```

Language(s) and/or frameworks involved:
JavaScript
NodeJs

### How to reproduce

```shell
1. Copy the `react-cra` directory into the root of an existing repo with an existing WORKSPACE file
2. move/delete top-level files & folders from the `react-cra` as needed
3. add `react-cra` to `pnpm-workspace.yaml`
4. run `pnpm i`
3. run `blaze build react-cra:build`
```

**Comment by kourtni** [comment]
Well, when I clone the entire repository and the `react-cra` example everything works as expected... So this isn't a bug at all. I guess, I just need to better understand how to configure the example to be runnable as a project within a monorepo (i.e. not having it's own `WORKSPACE` file).

**Comment by zacker330** [comment]
@kourtni I have same issue. Could you please add the WORKSPACE content to this example?
