### ISSUE TITLE
bazelrc: `common --keep_going` breaks `bazel shutdown`

### ISSUE THREAD

**Issue by jvolkman** [aspect-build/bazel-examples#5]
```
$ bazel shutdown
ERROR: --keep_going :: Unrecognized option: --keep_going
```
I've expanded it into separate lines for `build`, `fetch`, and `query` like to the `--noexperimental_check_output_files`, but maybe it applies to other commands as well.

As an aside, the UX around `common` is really aggravating.

**Comment by alexeagle** [comment]
Would be an awesome (though lengthy) project to fix the semantics of `common` in Bazel itself, to mean "all commands which accept these flags"
